# --- Estágio 1: Compilação (Builder) ---
FROM golang:1.26-alpine AS builder
RUN apk add --no-cache git gcc musl-dev
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o main ./cmd/server/main.go

# --- Estágio 2: Execução (Imagem Final) ---
FROM alpine:3.20

# 1. INSTALA O CHROMIUM E FONTES (Crucial para o chromedp rodar no Alpine)
RUN apk add --no-cache \
    ca-certificates \
    tzdata \
    chromium \
    ttf-freefont \
    font-noto

WORKDIR /app

# 2. Cria o usuário do sistema (Dica: o Chrome precisa de permissões de leitura/escrita)
RUN adduser -D -g '' appuser && \
    mkdir -p /app/templates /app/images && \
    chown -R appuser:appuser /app

# Copia o binário e o arquivo de configuração
COPY --from=builder /app/main .
COPY --from=builder /app/billing.json . 

# Copia as pastas de templates e imagens
COPY --from=builder /app/templates ./templates
COPY --from=builder /app/images ./images

# Altera a propriedade dos arquivos copiados para o appuser
RUN chown -R appuser:appuser /app

USER appuser
EXPOSE 8083

# 3. VARIÁVEL DE AMBIENTE (Opcional, ajuda o chromedp a localizar o Chromium se necessário)
ENV CHROME_BIN=/usr/bin/chromium-browser

CMD ["./main"]