version: "3.1"

services:    
  ephemeris:
    build: .
    container_name: ephemeris
    restart: always
    volumes:
      - .:/go/src/
    environment:
      MYSQL_DNS: root:root@tcp(mysql_ephemeris:3306)/ephemeris?charset=utf8&parseTime=True&loc=Local
      BUSINNESS_ID: cardoso&barbosa
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"

  mysql_ephemeris:
    image: mysql:8
    container_name: mysql_ephemeris
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ephemeris
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3310:3306"
 
