services:
  # Database service
  planner_db:
    image: postgres:latest
    container_name: planner_db_prod
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=planner
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - net-planner-prod
    ports:
      # Porta 5433 aberta para qualquer máquina da rede acessar o Postgres
      - "5433:5432"
    volumes:
      # Mantido o volume nomeado para garantir que seus dados nunca sumam
      - pg_production_data:/var/lib/postgresql/data

  # API service
  planner_api:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: planner_api_prod
    restart: always
    networks:
      - net-planner-prod
    ports:
      # MODIFICADO: Removido o 127.0.0.1.
      # Agora a porta 8083 está aberta globalmente. Qualquer máquina da sua
      # rede interna pode acessar o app digitando http://IP-DO-UBUNTU:8083
      - "8083:8083"
    # Sem blocos de 'environment' ou 'volumes', lendo seu arquivo interno de config.
    depends_on:
      - planner_db

volumes:
  pg_production_data:

networks:
  net-planner-prod:
    driver: bridge
