services:
  # Database service
  planner_db:
    image: postgres:latest
    container_name: planner_db_prod
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=planner
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - net-planner-prod
    ports:
      - "5433:5432"
    volumes:
      - pg_production_data:/var/lib/postgresql/data

  # API service
  planner_api:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: planner_api_prod
    restart: always
    networks:
      - net-planner-prod
    ports:
      - "8083:8083"
    volumes:
      # ADICIONADO: Sincroniza a pasta de logs local com a interna do container
      - ./tmp:/app/tmp
    depends_on:
      - planner_db

volumes:
  pg_production_data:

networks:
  net-planner-prod:
    driver: bridge
