# --- Estágio 1: Compilação (Builder) ---
FROM golang:1.26-alpine AS builder

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

# 1. Copia e baixa as dependências (Aproveita o cache do Docker)
COPY go.mod go.sum ./
RUN go mod download

# 2. Copia todo o código-fonte do projeto para o builder (incluindo o planner.json)
COPY . .

# 3. Compila o binário estático puro apontando para o seu cmd/server
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o main ./cmd/server/main.go


# --- Estágio 2: Execução (Imagem Final) ---
FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

# Roda com usuário comum por segurança
RUN adduser -D -g '' appuser

# 4. Copia o binário compilado do estágio anterior
COPY --from=builder /app/main .

# 5. CORRIGIDO: Copia o seu arquivo de configuração real localizado na raiz
COPY --from=builder /app/planner.json . 

USER appuser

# Informa a porta que a aplicação escuta
EXPOSE 8083

# Comando para iniciar a sua API
CMD ["./main"]

