services:
  # Database service
  db:
    image: postgres:latest
    container_name: billing_db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ephemeris
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql
  # API service
  api:
      build: .
      container_name: billing_api
      restart: always
      ports:
        - "8080:8080"
      volumes:
        - ${PWD}:/app
      environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_NAME=ephemeris    
      depends_on:
        - db
